[theme]
primaryColor="#0072B5"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
runOnSave = true

[browser]
gatherUsageStats = false

[global]
dataFrameSerialization = "arrow" 